# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d521fa6a13240664039b271ac74f42a54a8b5a5fcff2ad62718a3f56cba45983e8c8e4bd6600b81e09764f22f962405ee98e9cd09613c607894032c2fa3e3284

test:
  secret_key_base: 7cace93f2fe3389b8d0de9d86025ba7ec87a14f7897379a969289076d6f694525bee26e4b68e7260602fb68cb6c3247c9513138c8e823ae786b667471db526d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
